remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: RockByte Security Blog
description: Security Over The Rocks
google_analytics: G-67FNMPM222
github:
  is_project_page: false